# Generated by Django 3.2.8 on 2021-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='New', max_length=155),
        ),
    ]
