# Generated by Django 3.2.8 on 2021-10-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20211030_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
